version: '3'
name: netflix-conductor-workflow-engine
networks:
    microservice-core-service_default:
        external: true
services:
  conductor-server:
    environment:
      - CONFIG_PROP=config-local.properties
    image: ingwerludwig/conductor-server:latest
    expose:
      - 8080
    ports:
      - 8080:8080
    networks:
      - microservice-core-service_default
    healthcheck:
      test: ["CMD", "curl","-I" ,"-XGET", "http://localhost:8080/health"]
      interval: 60s
      timeout: 30s
      retries: 12
    links:
      - elasticsearch:es
    depends_on:
      - elasticsearch
    logging:
      driver: "json-file"
      options:
        max-size: "1k"
        max-file: "3"

  conductor-ui:
    environment:
      - WF_SERVER=http://conductor-server:8080/api/
    image: ingwerludwig/conductor-ui:latest
    ports:
      - 5000:5000
    networks:
      - microservice-core-service_default
    links:
      - conductor-server
    stdin_open: true

  elasticsearch:
    image: webhippie/elasticsearch:6.8
    environment:
      - ELASTICSEARCH_XPACK_SECURITY_ENABLED=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx1024m"
      - transport.host=0.0.0.0
      - discovery.type=single-node
      - xpack.security.enabled=false
    volumes:
      - esdata-conductor:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - microservice-core-service_default
    logging:
      driver: "json-file"
      options:
        max-size: "1k"
        max-file: "3"

volumes:
  esdata-conductor:
    driver: local
