version: '2.3.3'
name: netflix-conductor-workflow-engine
networks:
    microservice-core-service_default:
        external: true
services:
  conductor-server:
    container_name: conductor-server
    environment:
      - CONFIG_PROP=config-redis.properties
    image: ingwerludwig/conductor-server:latest
    expose:
      - 8080
    ports:
      - 8080:8080
    networks:
      - microservice-core-service_default
    healthcheck:
      test: ["CMD", "curl","-I" ,"-XGET", "http://localhost:8080/swagger-ui/index.html"]
      interval: 5s
      timeout: 30s
      retries: 50
    links:
      - conductor-elasticsearch:es
      - conductor-redis:rs
    depends_on:
      conductor-elasticsearch:
        condition: service_healthy
      conductor-redis:
        condition: service_healthy
    logging:
      driver: "json-file"
      options:
        max-size: "1k"
        max-file: "3"

  conductor-ui:
    container_name: conductor-ui
    environment:
      - WF_SERVER=http://conductor-server:8080/api/
    image: ingwerludwig/conductor-ui:latest
    ports:
      - 5000:5000
    networks:
      - microservice-core-service_default
    links:
      - conductor-server
    depends_on:
      conductor-server:
        condition: service_healthy
    stdin_open: true

  conductor-elasticsearch:
    container_name: conductor-elasticsearch
    image: webhippie/elasticsearch:6.8
    environment:
      - ELASTICSEARCH_XPACK_SECURITY_ENABLED=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx1024m"
      - transport.host=0.0.0.0
      - discovery.type=single-node
      - xpack.security.enabled=false
    volumes:
      - esdata-conductor:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
    healthcheck:
      test: >
        timeout 5 bash -c 'cat < /dev/null > /dev/tcp/localhost/9200' &&
        timeout 5 bash -c 'cat < /dev/null > /dev/tcp/localhost/9300'
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - microservice-core-service_default
    logging:
      driver: "json-file"
      options:
        max-size: "1k"
        max-file: "3"

  conductor-redis:
    container_name: conductor-redis
    image: redis:6.2.3-alpine
    volumes:
      - ../server/config/redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - 7379:6379
    networks:
      - microservice-core-service_default
    healthcheck:
      test: [ "CMD", "redis-cli","ping" ]

volumes:
  esdata-conductor:
    driver: local
